[tool.poetry]
name = "epam_2021_python_final"
version = "0.1.0"
description = "Final project for EPAM Python Autumn Program 2021"
authors = ["Andrey Shalaev <a.shalaev7125@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.9"
Flask = "^2.0.2"
SQLAlchemy = "^1.4.27"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
